- homework_week3/README.md
> READ파일에 조원 입력

- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/9
Function6 Done.
> Function6 Done

- src/main/java/kr/ac/cnu/web/games/blackjack/Deck.java
https://github.com/DohunHyun/spring-web-blackjack/issues/7
Done
> Function9 Done

- src/main/java/kr/ac/cnu/web/games/blackjack/Evaluator.java
- src/main/java/kr/ac/cnu/web/games/blackjack/Hand.java
- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
https://github.com/DohunHyun/spring-web-blackjack/issues/3
이제 블랙잭으로 이기면 1.5배를 받습니다.
> Function3 Done

- src/main/java/kr/ac/cnu/web/controller/api/BlackApiController.java
- src/main/java/kr/ac/cnu/web/games/blackjack/GameRoom.java
https://github.com/DohunHyun/spring-web-blackjack/issues/11
done
> Bugfix2 #11 done

- src/main/java/kr/ac/cnu/web/service/BlackjackService.java
https://github.com/DohunHyun/spring-web-blackjack/issues/5
done
> function7 #5 done

- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
https://github.com/DohunHyun/spring-web-blackjack/issues/8
Function5_done, nice~
> Function5_Done

- src/main/java/kr/ac/cnu/web/games/blackjack/GameRoom.java
- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
GameRoom 클래스에서 hit() 부분 수정했습니다.
> fixed error

- src/main/java/kr/ac/cnu/web/games/blackjack/GameRoom.java
https://github.com/DohunHyun/spring-web-blackjack/issues/10
BugFix1,2 Done
> BugFix1,2 Done

- src/main/java/kr/ac/cnu/web/controller/api/BlackApiController.java
- src/main/java/kr/ac/cnu/web/games/blackjack/GameRoom.java
- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
- src/main/java/kr/ac/cnu/web/service/BlackjackService.java
- src/main/resources/static/blackjack/index.html
Function1_웹 버튼 및 spring 매핑
미완성
> Function1_plus

- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
https://github.com/DohunHyun/spring-web-blackjack/issues/6
BugFix8 Done.
> Function8 Done

- src/main/java/kr/ac/cnu/web/controller/api/BlackApiController.java
- src/main/java/kr/ac/cnu/web/games/blackjack/GameRoom.java
- src/main/java/kr/ac/cnu/web/games/blackjack/Hand.java
- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
https://github.com/DohunHyun/spring-web-blackjack/issues/13
> bugfix4 & double down 추가 수정

- src/main/java/kr/ac/cnu/web/games/blackjack/GameRoom.java
- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
- src/main/java/kr/ac/cnu/web/service/BlackjackService.java
- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/1
Function1_DoubleDown-complete
힘들다.
>  Function1_DoubleDown-Complete 

- src/main/java/kr/ac/cnu/web/controller/api/BlackApiController.java
- src/main/java/kr/ac/cnu/web/games/blackjack/GameRoom.java
- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
- src/main/java/kr/ac/cnu/web/repository/UserRepository.java
- src/main/java/kr/ac/cnu/web/service/BlackjackService.java
- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/2
화면 상단에 돈과 이름 출력 완성
> view change

- src/main/java/kr/ac/cnu/web/controller/api/BlackApiController.java
- src/main/java/kr/ac/cnu/web/repository/UserRepository.java
- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/4
게임 화면 옆에 랭킹 뜹니다람쥐
> Ranking 완료^^

- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/35
* betting 금액 10000원 초과하여 deal 버튼 클릭시 double down 버튼 활성화 수정 완료했습니다.
> TestingResult_2 Done

- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/19
하하.. css 재밌네요
> css 어느정도 구현 완료

- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/44
https://github.com/DohunHyun/spring-web-blackjack/issues/43
두 가지 기능을 모두 구현하였습니다.
> index.html function changed

- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/46
Done.
> 최대 배팅 가능 금액이 넘은 경우 alert창 알려주기

- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/19
Main Page의 UI를 수정하였습니다.
> UI changed

- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/42
모두 완료하였습니다.
수고하셨습니다.
> Last modify

- src/main/java/kr/ac/cnu/web/games/blackjack/Player.java
- src/main/java/kr/ac/cnu/web/service/BlackjackService.java
- src/main/resources/static/blackjack/index.html
https://github.com/DohunHyun/spring-web-blackjack/issues/53
수정완료!
> BugFix_0원 배팅시 게임진행 안되도록
